.TH "_cookbook._unittest" 3 "Wed Sep 17 2014" "Version 0.0.0" "admin-linux" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_cookbook._unittest \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fB_UnitTestTestCase\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBfunc_1\fP"
.br
.ti -1c
.RI "def \fBfunc_2\fP"
.br
.ti -1c
.RI "def \fBfunc_3\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def _cookbook\&._unittest\&.func_1 ()"

.PP
.nf
No return.

.fi
.PP
 
.PP
Definition at line 52 of file _unittest\&.py\&.
.SS "def _cookbook\&._unittest\&.func_2 (a)"

.PP
.nf
Echo.

.fi
.PP
 
.PP
Definition at line 58 of file _unittest\&.py\&.
.SS "def _cookbook\&._unittest\&.func_3 ()"

.PP
.nf
Raise an exception (ValueError).

@exception ValueError

>>> func_4()
Traceback (most recent call last):
    ...
ValueError: error description

.fi
.PP
 
.PP
Definition at line 64 of file _unittest\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for admin-linux from the source code\&.
